# Generated by Django 4.1.13 on 2024-07-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(
                max_length=255, unique=True, verbose_name="Email пользователя"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="is_admin",
            field=models.BooleanField(
                default=False, verbose_name="Является ли user администратором"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="username",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Username пользователя"
            ),
        ),
    ]
